"""Priority US metro SEO pages for Chinese business markets (remote delivery from NYC)."""

from __future__ import annotations

# Each city: unique neighborhoods, search angles, industries — avoid thin duplicates of state pages.
US_CITIES: list[dict] = [
    # ── California ──
    {
        "slug": "los-angeles",
        "state_slug": "california",
        "name_en": "Los Angeles",
        "name_zh": "洛杉矶",
        "state_en": "California",
        "state_zh": "加利福尼亚州",
        "code": "CA",
        "neighborhoods_en": ["San Gabriel Valley", "Monterey Park", "Alhambra", "Rowland Heights", "Irvine corridor"],
        "neighborhoods_zh": ["圣盖博谷", "蒙特利公园", "阿罕布拉", "罗兰岗", "尔湾走廊"],
        "industries": ["restaurants", "beauty", "real estate", "legal", "healthcare"],
        "angle_zh": "圣盖博谷华人密度高，搜索常带城市名或 SGV；网站需中英双语与 Google 地图评价策略。",
        "angle_en": "SGV Chinese density is high — searches often include city names; sites need bilingual UX and Maps review strategy.",
    },
    {
        "slug": "san-francisco",
        "state_slug": "california",
        "name_en": "San Francisco Bay Area",
        "name_zh": "旧金山湾区",
        "state_en": "California",
        "state_zh": "加利福尼亚州",
        "code": "CA",
        "neighborhoods_en": ["San Francisco Chinatown", "Daly City", "Millbrae", "Cupertino", "Fremont"],
        "neighborhoods_zh": ["旧金山华埠", "戴利城", "米尔布雷", "库比蒂诺", "弗里蒙特"],
        "industries": ["tech", "restaurants", "education", "real estate", "healthcare"],
        "angle_zh": "湾区客户重视速度、移动端与专业感；科技与教育类站需清晰服务边界与双语案例。",
        "angle_en": "Bay Area buyers care about speed, mobile UX, and polish; tech/education sites need clear scope and bilingual proof.",
    },
    {
        "slug": "irvine",
        "state_slug": "california",
        "name_en": "Irvine / Orange County",
        "name_zh": "尔湾 / 橙县",
        "state_en": "California",
        "state_zh": "加利福尼亚州",
        "code": "CA",
        "neighborhoods_en": ["Irvine", "Tustin", "Costa Mesa", "Newport Beach", "Diamond Bar"],
        "neighborhoods_zh": ["尔湾", "塔斯廷", "科斯塔梅萨", "纽波特滩", "钻石吧"],
        "industries": ["restaurants", "beauty", "real estate", "education", "healthcare"],
        "angle_zh": "橙县华人家庭与新移民多，本地 SEO 常搜「Irvine 餐馆」「尔湾 房产」；适合中英双语站 + GBP。",
        "angle_en": "OC Chinese families search “Irvine restaurant / realtor”; bilingual sites + GBP perform well.",
    },
    {
        "slug": "san-diego",
        "state_slug": "california",
        "name_en": "San Diego",
        "name_zh": "圣地亚哥",
        "state_en": "California",
        "state_zh": "加利福尼亚州",
        "code": "CA",
        "neighborhoods_en": ["Convoy District", "Miramar", "La Jolla", "Chula Vista"],
        "neighborhoods_zh": ["Convoy 亚洲区", "米拉马", "拉霍亚", "丘拉维斯塔"],
        "industries": ["restaurants", "tourism", "healthcare", "beauty"],
        "angle_zh": "Convoy 亚洲餐饮聚集；旅游与本地客流并存，网站需订座/外卖与地图双优化。",
        "angle_en": "Convoy Asian dining cluster — balance tourist and local intent with booking/Maps optimization.",
    },
    # ── Texas ──
    {
        "slug": "houston",
        "state_slug": "texas",
        "name_en": "Houston",
        "name_zh": "休斯顿",
        "state_en": "Texas",
        "state_zh": "德克萨斯州",
        "code": "TX",
        "neighborhoods_en": ["Chinatown / Bellaire", "Sugar Land", "Katy", "Pearland", "Fort Bend"],
        "neighborhoods_zh": ["华埠 / Bellaire", "舒格兰", "凯蒂", "皮尔兰", "Fort Bend"],
        "industries": ["restaurants", "real estate", "healthcare", "oil services", "beauty"],
        "angle_zh": "休斯顿华人社区沿 Bellaire / Sugar Land 延伸，搜索常带郊区名；多城服务半径要写清。",
        "angle_en": "Houston Chinese corridor runs Bellaire–Sugar Land; spell out suburb names and service radius.",
    },
    {
        "slug": "dallas",
        "state_slug": "texas",
        "name_en": "Dallas / Plano",
        "name_zh": "达拉斯 / 普莱诺",
        "state_en": "Texas",
        "state_zh": "德克萨斯州",
        "code": "TX",
        "neighborhoods_en": ["Plano", "Richardson", "Frisco", "Carrollton", "Dallas"],
        "neighborhoods_zh": ["普莱诺", "理查森", "弗里斯科", "卡罗尔顿", "达拉斯"],
        "industries": ["restaurants", "real estate", "beauty", "healthcare", "education"],
        "angle_zh": "北达拉斯华人聚 Plano / Richardson，关键词多用郊区名而非只写 Dallas。",
        "angle_en": "North Dallas Chinese density is in Plano/Richardson — optimize suburb keywords, not only “Dallas”.",
    },
    {
        "slug": "austin",
        "state_slug": "texas",
        "name_en": "Austin",
        "name_zh": "奥斯汀",
        "state_en": "Texas",
        "state_zh": "德克萨斯州",
        "code": "TX",
        "neighborhoods_en": ["North Austin", "Round Rock", "Cedar Park", "Domain area"],
        "neighborhoods_zh": ["北奥斯汀", "朗德罗克", "锡达帕克", "Domain 商圈"],
        "industries": ["tech", "restaurants", "real estate", "healthcare"],
        "angle_zh": "奥斯汀科技与新移民增长快，网站强调移动端、速度与英文为主+中文核心页。",
        "angle_en": "Fast-growing tech/immigrant market — prioritize mobile speed and English-first with Chinese core pages.",
    },
    # ── Florida ──
    {
        "slug": "miami",
        "state_slug": "florida",
        "name_en": "Miami",
        "name_zh": "迈阿密",
        "state_en": "Florida",
        "state_zh": "佛罗里达州",
        "code": "FL",
        "neighborhoods_en": ["Aventura", "Sunny Isles", "Brickell", "Coral Gables", "Doral"],
        "neighborhoods_zh": ["阿文图拉", "阳光岛", "Brickell", "科勒尔盖布尔斯", "多拉尔"],
        "industries": ["real estate", "restaurants", "tourism", "beauty", "legal"],
        "angle_zh": "迈阿密多语市场（英/西/中），华人客户常搜房产与餐饮；网站需清晰语言切换与地图。",
        "angle_en": "Multilingual market (EN/ES/ZH) — Chinese clients often search real estate and dining; clear language UX + Maps.",
    },
    {
        "slug": "orlando",
        "state_slug": "florida",
        "name_en": "Orlando",
        "name_zh": "奥兰多",
        "state_en": "Florida",
        "state_zh": "佛罗里达州",
        "code": "FL",
        "neighborhoods_en": ["Downtown Orlando", "Winter Park", "Dr. Phillips", "Lake Nona", "Kissimmee"],
        "neighborhoods_zh": ["奥兰多市中心", "冬园", "Dr. Phillips", "Lake Nona", "基西米"],
        "industries": ["tourism", "restaurants", "real estate", "healthcare"],
        "angle_zh": "旅游与本地客并存；餐馆/酒店站需多语言、订座与季节性 Google Ads。",
        "angle_en": "Tourist + local mix — restaurants/hotels need multilingual booking and seasonal Ads.",
    },
    {
        "slug": "tampa",
        "state_slug": "florida",
        "name_en": "Tampa Bay",
        "name_zh": "坦帕湾",
        "state_en": "Florida",
        "state_zh": "佛罗里达州",
        "code": "FL",
        "neighborhoods_en": ["Tampa", "St. Petersburg", "Clearwater", "Brandon"],
        "neighborhoods_zh": ["坦帕", "圣彼德斯堡", "清水湾", "布兰登"],
        "industries": ["restaurants", "healthcare", "real estate", "retail"],
        "angle_zh": "坦帕湾华人社区增长中，本地 SEO 用 Tampa / St. Pete + 行业组合词。",
        "angle_en": "Growing Chinese community — target Tampa / St. Pete + industry keyword pairs.",
    },
    # ── Pennsylvania ──
    {
        "slug": "philadelphia",
        "state_slug": "pennsylvania",
        "name_en": "Philadelphia",
        "name_zh": "费城",
        "state_en": "Pennsylvania",
        "state_zh": "宾夕法尼亚州",
        "code": "PA",
        "neighborhoods_en": ["Chinatown", "University City", "King of Prussia", "Main Line", "Cherry Hill NJ"],
        "neighborhoods_zh": ["华埠", "大学城", "普鲁士王", "Main Line", "新泽西樱桃山"],
        "industries": ["restaurants", "healthcare", "education", "legal", "beauty"],
        "angle_zh": "费城华埠 + 郊区 Main Line / KOP；跨州客户（PA/NJ）需写清服务范围。",
        "angle_en": "Philly Chinatown + Main Line / KOP suburbs; PA–NJ cross-border service areas must be explicit.",
    },
    # ── Boston / Massachusetts ──
    {
        "slug": "boston",
        "state_slug": "massachusetts",
        "name_en": "Boston",
        "name_zh": "波士顿",
        "state_en": "Massachusetts",
        "state_zh": "马萨诸塞州",
        "code": "MA",
        "neighborhoods_en": ["Chinatown", "Quincy", "Malden", "Cambridge", "Brookline"],
        "neighborhoods_zh": ["华埠", "昆西", "莫尔登", "剑桥", "布鲁克莱恩"],
        "industries": ["restaurants", "education", "healthcare", "tech", "legal"],
        "angle_zh": "昆西、莫尔登华人密度高；学生与家庭客群并存，关键词常带 Quincy / Malden。",
        "angle_en": "Quincy and Malden have dense Chinese communities — pair city names with student vs family intent.",
    },
    # ── Seattle / Washington ──
    {
        "slug": "seattle",
        "state_slug": "washington",
        "name_en": "Seattle",
        "name_zh": "西雅图",
        "state_en": "Washington",
        "state_zh": "华盛顿州",
        "code": "WA",
        "neighborhoods_en": ["International District", "Beacon Hill", "Bellevue", "Redmond", "Kirkland"],
        "neighborhoods_zh": ["国际区", "灯塔山", "贝尔维尤", "雷德蒙德", "柯克兰"],
        "industries": ["tech", "restaurants", "real estate", "healthcare", "education"],
        "angle_zh": "东区 Bellevue / Redmond 华人与科技从业者多；网站需专业感与本地地图双覆盖。",
        "angle_en": "Eastside Bellevue/Redmond Chinese + tech professionals — polish + local Maps coverage both matter.",
    },
    {
        "slug": "bellevue",
        "state_slug": "washington",
        "name_en": "Bellevue",
        "name_zh": "贝尔维尤",
        "state_en": "Washington",
        "state_zh": "华盛顿州",
        "code": "WA",
        "neighborhoods_en": ["Downtown Bellevue", "Factoria", "Crossroads", "Newcastle", "Sammamish"],
        "neighborhoods_zh": ["贝尔维尤市中心", "Factoria", "十字路口", "纽卡斯尔", "萨马米什"],
        "industries": ["restaurants", "beauty", "real estate", "education", "healthcare"],
        "angle_zh": "贝尔维尤是大西雅图华人消费中心，适合「Bellevue + 行业」本地词与双语站。",
        "angle_en": "Bellevue is a Chinese retail hub for greater Seattle — strong “Bellevue + service” local keywords.",
    },
]

assert len(US_CITIES) >= 14, f"Expected priority metros, got {len(US_CITIES)}"
