"""US states + DC for 70NYC remote SEO landing pages (50 states + Washington DC)."""

from __future__ import annotations

# slug, code, name_en, name_zh, cities (Chinese-community / major metros), industries
US_STATES: list[dict] = [
    {
        "slug": "alabama",
        "code": "AL",
        "name_en": "Alabama",
        "name_zh": "阿拉巴马州",
        "cities": ["Birmingham", "Huntsville", "Mobile"],
        "cities_zh": ["伯明翰", "亨茨维尔", "莫比尔"],
        "industries": ["restaurants", "healthcare", "retail"],
    },
    {
        "slug": "alaska",
        "code": "AK",
        "name_en": "Alaska",
        "name_zh": "阿拉斯加州",
        "cities": ["Anchorage", "Fairbanks", "Juneau"],
        "cities_zh": ["安克雷奇", "费尔班克斯", "朱诺"],
        "industries": ["tourism", "restaurants", "professional services"],
    },
    {
        "slug": "arizona",
        "code": "AZ",
        "name_en": "Arizona",
        "name_zh": "亚利桑那州",
        "cities": ["Phoenix", "Tucson", "Scottsdale", "Mesa"],
        "cities_zh": ["凤凰城", "图森", "斯科茨代尔", "梅萨"],
        "industries": ["restaurants", "real estate", "medical spa", "contractors"],
    },
    {
        "slug": "arkansas",
        "code": "AR",
        "name_en": "Arkansas",
        "name_zh": "阿肯色州",
        "cities": ["Little Rock", "Fayetteville", "Bentonville"],
        "cities_zh": ["小石城", "费耶特维尔", "本顿维尔"],
        "industries": ["restaurants", "retail", "healthcare"],
    },
    {
        "slug": "california",
        "code": "CA",
        "name_en": "California",
        "name_zh": "加利福尼亚州",
        "cities": ["Los Angeles", "San Francisco", "San Jose", "San Diego", "Irvine", "Sacramento"],
        "cities_zh": ["洛杉矶", "旧金山", "圣何塞", "圣地亚哥", "尔湾", "萨克拉门托"],
        "industries": ["restaurants", "beauty", "tech", "real estate", "legal"],
    },
    {
        "slug": "colorado",
        "code": "CO",
        "name_en": "Colorado",
        "name_zh": "科罗拉多州",
        "cities": ["Denver", "Aurora", "Boulder", "Colorado Springs"],
        "cities_zh": ["丹佛", "奥罗拉", "博尔德", "科泉"],
        "industries": ["restaurants", "healthcare", "contractors", "tourism"],
    },
    {
        "slug": "connecticut",
        "code": "CT",
        "name_en": "Connecticut",
        "name_zh": "康涅狄格州",
        "cities": ["Stamford", "New Haven", "Hartford", "Greenwich"],
        "cities_zh": ["斯坦福德", "纽黑文", "哈特福德", "格林尼治"],
        "industries": ["legal", "finance", "restaurants", "healthcare"],
    },
    {
        "slug": "delaware",
        "code": "DE",
        "name_en": "Delaware",
        "name_zh": "特拉华州",
        "cities": ["Wilmington", "Dover", "Newark"],
        "cities_zh": ["威尔明顿", "多佛", "纽瓦克"],
        "industries": ["finance", "legal", "restaurants"],
    },
    {
        "slug": "florida",
        "code": "FL",
        "name_en": "Florida",
        "name_zh": "佛罗里达州",
        "cities": ["Miami", "Orlando", "Tampa", "Fort Lauderdale", "Jacksonville"],
        "cities_zh": ["迈阿密", "奥兰多", "坦帕", "劳德代尔堡", "杰克逊维尔"],
        "industries": ["restaurants", "real estate", "tourism", "beauty", "healthcare"],
    },
    {
        "slug": "georgia",
        "code": "GA",
        "name_en": "Georgia",
        "name_zh": "乔治亚州",
        "cities": ["Atlanta", "Marietta", "Duluth", "Johns Creek", "Savannah"],
        "cities_zh": ["亚特兰大", "玛丽埃塔", "杜鲁斯", "约翰斯克里克", "萨凡纳"],
        "industries": ["restaurants", "beauty", "real estate", "contractors"],
    },
    {
        "slug": "hawaii",
        "code": "HI",
        "name_en": "Hawaii",
        "name_zh": "夏威夷州",
        "cities": ["Honolulu", "Pearl City", "Hilo"],
        "cities_zh": ["檀香山", "珍珠港", "希洛"],
        "industries": ["tourism", "restaurants", "retail"],
    },
    {
        "slug": "idaho",
        "code": "ID",
        "name_en": "Idaho",
        "name_zh": "爱达荷州",
        "cities": ["Boise", "Meridian", "Nampa"],
        "cities_zh": ["博伊西", "梅里迪安", "南帕"],
        "industries": ["restaurants", "contractors", "healthcare"],
    },
    {
        "slug": "illinois",
        "code": "IL",
        "name_en": "Illinois",
        "name_zh": "伊利诺伊州",
        "cities": ["Chicago", "Naperville", "Schaumburg", "Evanston"],
        "cities_zh": ["芝加哥", "内珀维尔", "绍姆堡", "埃文斯顿"],
        "industries": ["restaurants", "legal", "beauty", "healthcare"],
    },
    {
        "slug": "indiana",
        "code": "IN",
        "name_en": "Indiana",
        "name_zh": "印第安纳州",
        "cities": ["Indianapolis", "Fort Wayne", "Carmel"],
        "cities_zh": ["印第安纳波利斯", "韦恩堡", "卡梅尔"],
        "industries": ["restaurants", "healthcare", "retail"],
    },
    {
        "slug": "iowa",
        "code": "IA",
        "name_en": "Iowa",
        "name_zh": "艾奥瓦州",
        "cities": ["Des Moines", "Cedar Rapids", "Iowa City"],
        "cities_zh": ["得梅因", "锡达拉皮兹", "艾奥瓦城"],
        "industries": ["restaurants", "healthcare", "agriculture services"],
    },
    {
        "slug": "kansas",
        "code": "KS",
        "name_en": "Kansas",
        "name_zh": "堪萨斯州",
        "cities": ["Kansas City", "Wichita", "Overland Park"],
        "cities_zh": ["堪萨斯城", "威奇托", "欧弗兰帕克"],
        "industries": ["restaurants", "healthcare", "retail"],
    },
    {
        "slug": "kentucky",
        "code": "KY",
        "name_en": "Kentucky",
        "name_zh": "肯塔基州",
        "cities": ["Louisville", "Lexington", "Bowling Green"],
        "cities_zh": ["路易斯维尔", "列克星敦", "鲍灵格林"],
        "industries": ["restaurants", "healthcare", "retail"],
    },
    {
        "slug": "louisiana",
        "code": "LA",
        "name_en": "Louisiana",
        "name_zh": "路易斯安那州",
        "cities": ["New Orleans", "Baton Rouge", "Metairie"],
        "cities_zh": ["新奥尔良", "巴吞鲁日", "梅泰里"],
        "industries": ["restaurants", "tourism", "healthcare"],
    },
    {
        "slug": "maine",
        "code": "ME",
        "name_en": "Maine",
        "name_zh": "缅因州",
        "cities": ["Portland", "Bangor", "Lewiston"],
        "cities_zh": ["波特兰", "班戈", "刘易斯顿"],
        "industries": ["tourism", "restaurants", "retail"],
    },
    {
        "slug": "maryland",
        "code": "MD",
        "name_en": "Maryland",
        "name_zh": "马里兰州",
        "cities": ["Rockville", "Gaithersburg", "Baltimore", "Bethesda"],
        "cities_zh": ["罗克维尔", "盖瑟斯堡", "巴尔的摩", "贝塞斯达"],
        "industries": ["restaurants", "healthcare", "legal", "beauty"],
    },
    {
        "slug": "massachusetts",
        "code": "MA",
        "name_en": "Massachusetts",
        "name_zh": "马萨诸塞州",
        "cities": ["Boston", "Quincy", "Cambridge", "Malden"],
        "cities_zh": ["波士顿", "昆西", "剑桥", "莫尔登"],
        "industries": ["restaurants", "education", "healthcare", "tech"],
    },
    {
        "slug": "michigan",
        "code": "MI",
        "name_en": "Michigan",
        "name_zh": "密歇根州",
        "cities": ["Detroit", "Ann Arbor", "Troy", "Grand Rapids"],
        "cities_zh": ["底特律", "安娜堡", "特洛伊", "大急流城"],
        "industries": ["restaurants", "auto services", "healthcare"],
    },
    {
        "slug": "minnesota",
        "code": "MN",
        "name_en": "Minnesota",
        "name_zh": "明尼苏达州",
        "cities": ["Minneapolis", "Saint Paul", "Eden Prairie"],
        "cities_zh": ["明尼阿波利斯", "圣保罗", "伊甸草原"],
        "industries": ["restaurants", "healthcare", "retail"],
    },
    {
        "slug": "mississippi",
        "code": "MS",
        "name_en": "Mississippi",
        "name_zh": "密西西比州",
        "cities": ["Jackson", "Gulfport", "Southaven"],
        "cities_zh": ["杰克逊", "格尔夫波特", "绍斯黑文"],
        "industries": ["restaurants", "healthcare", "retail"],
    },
    {
        "slug": "missouri",
        "code": "MO",
        "name_en": "Missouri",
        "name_zh": "密苏里州",
        "cities": ["St. Louis", "Kansas City", "Columbia"],
        "cities_zh": ["圣路易斯", "堪萨斯城", "哥伦比亚"],
        "industries": ["restaurants", "healthcare", "education"],
    },
    {
        "slug": "montana",
        "code": "MT",
        "name_en": "Montana",
        "name_zh": "蒙大拿州",
        "cities": ["Billings", "Missoula", "Bozeman"],
        "cities_zh": ["比林斯", "米苏拉", "博兹曼"],
        "industries": ["tourism", "restaurants", "contractors"],
    },
    {
        "slug": "nebraska",
        "code": "NE",
        "name_en": "Nebraska",
        "name_zh": "内布拉斯加州",
        "cities": ["Omaha", "Lincoln", "Bellevue"],
        "cities_zh": ["奥马哈", "林肯", "贝尔维尤"],
        "industries": ["restaurants", "healthcare", "retail"],
    },
    {
        "slug": "nevada",
        "code": "NV",
        "name_en": "Nevada",
        "name_zh": "内华达州",
        "cities": ["Las Vegas", "Henderson", "Reno", "Summerlin"],
        "cities_zh": ["拉斯维加斯", "亨德森", "里诺", "夏默林"],
        "industries": ["restaurants", "tourism", "real estate", "beauty"],
    },
    {
        "slug": "new-hampshire",
        "code": "NH",
        "name_en": "New Hampshire",
        "name_zh": "新罕布什尔州",
        "cities": ["Manchester", "Nashua", "Concord"],
        "cities_zh": ["曼彻斯特", "纳舒厄", "康科德"],
        "industries": ["restaurants", "retail", "healthcare"],
    },
    {
        "slug": "new-jersey",
        "code": "NJ",
        "name_en": "New Jersey",
        "name_zh": "新泽西州",
        "cities": ["Edison", "Jersey City", "Fort Lee", "Princeton", "Newark"],
        "cities_zh": ["爱迪生", "泽西市", "李堡", "普林斯顿", "纽瓦克"],
        "industries": ["restaurants", "beauty", "real estate", "legal", "healthcare"],
    },
    {
        "slug": "new-mexico",
        "code": "NM",
        "name_en": "New Mexico",
        "name_zh": "新墨西哥州",
        "cities": ["Albuquerque", "Santa Fe", "Las Cruces"],
        "cities_zh": ["阿尔伯克基", "圣达菲", "拉斯克鲁塞斯"],
        "industries": ["restaurants", "tourism", "healthcare"],
    },
    {
        "slug": "new-york-state",
        "code": "NY",
        "name_en": "New York State",
        "name_zh": "纽约州（全州）",
        "cities": ["Buffalo", "Rochester", "Albany", "Syracuse", "White Plains"],
        "cities_zh": ["水牛城", "罗切斯特", "奥尔巴尼", "锡拉丘兹", "白原"],
        "industries": ["restaurants", "healthcare", "education", "legal"],
        "note_zh": "大纽约六区请见本地服务区域页；本页面向纽约州其他城市与远程客户。",
        "note_en": "For NYC metro boroughs, see our local area pages; this page covers upstate and other NY cities via remote delivery.",
    },
    {
        "slug": "north-carolina",
        "code": "NC",
        "name_en": "North Carolina",
        "name_zh": "北卡罗来纳州",
        "cities": ["Charlotte", "Raleigh", "Durham", "Cary", "Greensboro"],
        "cities_zh": ["夏洛特", "罗利", "达勒姆", "凯里", "格林斯伯勒"],
        "industries": ["restaurants", "tech", "healthcare", "real estate"],
    },
    {
        "slug": "north-dakota",
        "code": "ND",
        "name_en": "North Dakota",
        "name_zh": "北达科他州",
        "cities": ["Fargo", "Bismarck", "Grand Forks"],
        "cities_zh": ["法戈", "俾斯麦", "大福克斯"],
        "industries": ["restaurants", "healthcare", "energy services"],
    },
    {
        "slug": "ohio",
        "code": "OH",
        "name_en": "Ohio",
        "name_zh": "俄亥俄州",
        "cities": ["Columbus", "Cleveland", "Cincinnati", "Dayton"],
        "cities_zh": ["哥伦布", "克利夫兰", "辛辛那提", "代顿"],
        "industries": ["restaurants", "healthcare", "education", "retail"],
    },
    {
        "slug": "oklahoma",
        "code": "OK",
        "name_en": "Oklahoma",
        "name_zh": "俄克拉荷马州",
        "cities": ["Oklahoma City", "Tulsa", "Norman"],
        "cities_zh": ["俄克拉荷马城", "塔尔萨", "诺曼"],
        "industries": ["restaurants", "healthcare", "retail"],
    },
    {
        "slug": "oregon",
        "code": "OR",
        "name_en": "Oregon",
        "name_zh": "俄勒冈州",
        "cities": ["Portland", "Beaverton", "Eugene", "Salem"],
        "cities_zh": ["波特兰", "比弗顿", "尤金", "塞勒姆"],
        "industries": ["restaurants", "tech", "retail", "healthcare"],
    },
    {
        "slug": "pennsylvania",
        "code": "PA",
        "name_en": "Pennsylvania",
        "name_zh": "宾夕法尼亚州",
        "cities": ["Philadelphia", "Pittsburgh", "Allentown", "King of Prussia"],
        "cities_zh": ["费城", "匹兹堡", "阿伦敦", "普鲁士王"],
        "industries": ["restaurants", "healthcare", "education", "legal"],
    },
    {
        "slug": "rhode-island",
        "code": "RI",
        "name_en": "Rhode Island",
        "name_zh": "罗得岛州",
        "cities": ["Providence", "Warwick", "Cranston"],
        "cities_zh": ["普罗维登斯", "沃里克", "克兰斯顿"],
        "industries": ["restaurants", "healthcare", "education"],
    },
    {
        "slug": "south-carolina",
        "code": "SC",
        "name_en": "South Carolina",
        "name_zh": "南卡罗来纳州",
        "cities": ["Charleston", "Columbia", "Greenville", "Myrtle Beach"],
        "cities_zh": ["查尔斯顿", "哥伦比亚", "格林维尔", "默特尔比奇"],
        "industries": ["restaurants", "tourism", "manufacturing services"],
    },
    {
        "slug": "south-dakota",
        "code": "SD",
        "name_en": "South Dakota",
        "name_zh": "南达科他州",
        "cities": ["Sioux Falls", "Rapid City", "Aberdeen"],
        "cities_zh": ["苏福尔斯", "拉皮德城", "阿伯丁"],
        "industries": ["restaurants", "healthcare", "tourism"],
    },
    {
        "slug": "tennessee",
        "code": "TN",
        "name_en": "Tennessee",
        "name_zh": "田纳西州",
        "cities": ["Nashville", "Memphis", "Knoxville", "Chattanooga"],
        "cities_zh": ["纳什维尔", "孟菲斯", "诺克斯维尔", "查塔努加"],
        "industries": ["restaurants", "healthcare", "tourism", "music business"],
    },
    {
        "slug": "texas",
        "code": "TX",
        "name_en": "Texas",
        "name_zh": "德克萨斯州",
        "cities": ["Houston", "Dallas", "Austin", "Plano", "Sugar Land", "San Antonio"],
        "cities_zh": ["休斯顿", "达拉斯", "奥斯汀", "普莱诺", "舒格兰", "圣安东尼奥"],
        "industries": ["restaurants", "real estate", "oil services", "beauty", "legal"],
    },
    {
        "slug": "utah",
        "code": "UT",
        "name_en": "Utah",
        "name_zh": "犹他州",
        "cities": ["Salt Lake City", "Provo", "Park City"],
        "cities_zh": ["盐湖城", "普罗沃", "帕克城"],
        "industries": ["tech", "tourism", "restaurants"],
    },
    {
        "slug": "vermont",
        "code": "VT",
        "name_en": "Vermont",
        "name_zh": "佛蒙特州",
        "cities": ["Burlington", "South Burlington", "Montpelier"],
        "cities_zh": ["伯灵顿", "南伯灵顿", "蒙彼利埃"],
        "industries": ["tourism", "restaurants", "retail"],
    },
    {
        "slug": "virginia",
        "code": "VA",
        "name_en": "Virginia",
        "name_zh": "弗吉尼亚州",
        "cities": ["Fairfax", "Vienna", "Richmond", "Virginia Beach", "Arlington"],
        "cities_zh": ["费尔法克斯", "维也纳", "里士满", "弗吉尼亚海滩", "阿灵顿"],
        "industries": ["restaurants", "government contractors", "healthcare", "beauty"],
    },
    {
        "slug": "washington",
        "code": "WA",
        "name_en": "Washington",
        "name_zh": "华盛顿州",
        "cities": ["Seattle", "Bellevue", "Redmond", "Tacoma", "Kirkland"],
        "cities_zh": ["西雅图", "贝尔维尤", "雷德蒙德", "塔科马", "柯克兰"],
        "industries": ["tech", "restaurants", "real estate", "healthcare"],
    },
    {
        "slug": "west-virginia",
        "code": "WV",
        "name_en": "West Virginia",
        "name_zh": "西弗吉尼亚州",
        "cities": ["Charleston", "Morgantown", "Huntington"],
        "cities_zh": ["查尔斯顿", "摩根敦", "亨廷顿"],
        "industries": ["healthcare", "restaurants", "education"],
    },
    {
        "slug": "wisconsin",
        "code": "WI",
        "name_en": "Wisconsin",
        "name_zh": "威斯康星州",
        "cities": ["Milwaukee", "Madison", "Green Bay"],
        "cities_zh": ["密尔沃基", "麦迪逊", "绿湾"],
        "industries": ["restaurants", "healthcare", "education"],
    },
    {
        "slug": "wyoming",
        "code": "WY",
        "name_en": "Wyoming",
        "name_zh": "怀俄明州",
        "cities": ["Cheyenne", "Casper", "Jackson"],
        "cities_zh": ["夏延", "卡斯珀", "杰克逊"],
        "industries": ["tourism", "energy services", "restaurants"],
    },
    {
        "slug": "washington-dc",
        "code": "DC",
        "name_en": "Washington, D.C.",
        "name_zh": "华盛顿哥伦比亚特区",
        "cities": ["Washington DC", "Georgetown", "Capitol Hill"],
        "cities_zh": ["华盛顿特区", "乔治城", "国会山"],
        "industries": ["legal", "government contractors", "restaurants", "ngo"],
    },
]

assert len(US_STATES) == 51, f"Expected 51 entries, got {len(US_STATES)}"
